OC.L10N.register(
    "llm",
    {
    "Large language model" : "نموذج لُغَوي language model كبير ",
    "Local GPT4ALL Large language model" : "نموذج لغوي كبير محلي GPT4ALL",
    "TextProcessing provider using a GPT4All Large Language Model by Nomic AI that runs locally on CPU" : "مزود معالجة النصوص باستعمال GPT4All Large Language Model من Nomic AI الذي يعمل محليًا على وحدة المعالجة المركزية",
    "A TextProcessing provider using a GPT4All Large Language Model by Nomic AI  that runs locally on CPU\n\nThe models run completely on your machine. No private data leaves your servers.\n\nAfter installing this app you will need to run\n\n    occ llm:download-models\n\nRequirements:\n\n* x86 CPU\n* GNU lib C (musl is not supported)\n* Python 3.10+\n\n## Ethical AI Rating\n### Rating: 🟢\n\nPositive:\n* the software for training and inference of this model is open source\n* the trained model is freely available, and thus can be ran on-premises\n* the training data is freely available, making it possible to check or correct for bias or optimise the performance and CO2 usage.\n\nLearn more about the Nextcloud Ethical AI Rating [in our blog](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/)." : "مزوِّد معالجة النصوص باستعمال GPT4All Large Language Model من Nomic AI يعمل محليًا على وحدة المعالجة المركزية \n\nتعمل النماذج بالكامل على جهازك. لا توجد بيانات خاصة تترك خوادمك. \n\nبعد تثبيت هذا التطبيق، ستحتاج إلى تنفيذ الأمر: \nocc llm:download-models\nالمتطلبات: \n* x86 CPU\n* مكتبة GNU lib C (musl غير مدعوم) \n* بايثون 3.10 + \n\n## تصنيف الذكاء الاصطناعي الأخلاقي \n\n### التقييم: 🟢 \n\nالإيجابيات: \n* برنامج التدريب والاستدلال لهذا النموذج مفتوح المصدر \n* النموذج المدرَّب متاح مانًا ، و بالتالي يمكن تشغيله محليًا \n* بيانات التدريب متاحة مجانًا، مما يجعل من الممكن التحقق من التحيز أو تصحيحه أو تحسين الأداء و استهلاك ثاني أكسيد الكربون CO2. \n\nتعرف على المزيد حول تصنيف Nextcloud Ethical AI [في مدونتنا] (https://nextcloud.com/blog/nextcloud-ethical-ai-rating/).",
    "Status" : "الحاله",
    "Machine learning models have been downloaded successfully." : "تمّ تحميل نماذج تعلّم الآلة بنجاح.",
    "The machine learning models still need to be downloaded (see below)." : "نماذج تعلّم الآلة لم يتم تحميلها بعدُ. (أنظر أدناه).",
    "Could not execute python. You may need to set the path to a working executable manually. (See below.)" : "تعذر تنفيذ بيثون. قد تحتاج إلى تعيين المسار إلى ملف قابل للتنفيذ يعمل يدويًا. (انظر أدناه.)",
    "Background Jobs are not executed via cron. This app requires background jobs to be executed via cron." : "مهام الخلفية لا تعمل حاليّاً عبر cron. هذا التطبيق يستلزم تشغيل مهام الخلفية عبر cron.",
    "The app was installed successfully and will transcribe files in background processes on request." : "تمّ تنصيب هذا التطبيق بنجاح و هو مستعد لاستنساخ الملفات في الخلفية عند الطلب.",
    "Inference settings" : "إعدادات الاستدلال inference",
    "The number of threads to use for inference (more is faster)" : "عدد الخيوط threads المراد استخدامها للاستدلال (كلما زاد عددها، زادت سرعة الأداء)",
    "Python" : "Python",
    "Checking Python" : "إختبار بايتون ",
    "Could not execute Python. You may need to set the path to a working executable manually." : "تعذر تنفيذ بايثون. قد تحتاج إلى تعيين المسار إلى ملف قابل للتنفيذ يعمل يدويًا.",
    "Python executable executed successfully and setup works." : "تم تنفيذ برنامج Python بنجاح، و الإعداد يعمل.",
    "If Python is not found automatically on your system for some reason you can set the path to the Python executable here. If you change this value, make sure to run occ maintenance:repair afterwards." : "إذا لم يتم العثور على Python تلقائيًا على نظامك لسببٍ ما، يمكنك تعيين المسار إلى Python التنفيذي هنا. إذا قمت بتغيير هذه القيمة، فقم لاحقاً بتشغيل الأمر السطري: \nocc maintenance:repair ",
    "Failed to load settings" : "إخفاق في تحميل الإعدادات",
    "Failed to save settings" : "إخفاق في حفظ الإعدادات"
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
