OC.L10N.register(
    "llm",
    {
    "Large language model" : "Велики језички модел",
    "Local GPT4ALL Large language model" : "Локални GPT4ALL Велики језички модел",
    "TextProcessing provider using a GPT4All Large Language Model by Nomic AI that runs locally on CPU" : "Добављач TextProcessing услуге који користи GPT4All Large Language Model компаније Nomic AI и који се извршава на локалном CPU",
    "A TextProcessing provider using a GPT4All Large Language Model by Nomic AI  that runs locally on CPU\n\nThe models run completely on your machine. No private data leaves your servers.\n\nAfter installing this app you will need to run\n\n    occ llm:download-models\n\nRequirements:\n\n* x86 CPU\n* GNU lib C (musl is not supported)\n* Python 3.10+\n\n## Ethical AI Rating\n### Rating: 🟢\n\nPositive:\n* the software for training and inference of this model is open source\n* the trained model is freely available, and thus can be ran on-premises\n* the training data is freely available, making it possible to check or correct for bias or optimise the performance and CO2 usage.\n\nLearn more about the Nextcloud Ethical AI Rating [in our blog](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/)." : "Добављач TextProcessing услуге који користи GPT4All Large Language Model компаније Nomic AI и који се локално извршава на CPU\n\nМодели се у потпуности извршавају на вашој машини. Приватни подаци никада не напуштају ваш сервер.\n\nКада инсталирате ову апликацију мораћете да извршите\n\n    occ llm:download-models\n\nЗахтеви:\n\n* x86 CPU\n* GNU lib C (musl се не подржава)\n* Python 3.10+\n\n## Етичко рангирање AI\n### Рангирање: 🟢\n\nДобре стране:\n* софтвер за тренирање и закључивање овог модела је отвореног кода\n* тренирани модел је јавно доступан, па може да се извршава на вашем хардверу\n* подаци за тренирање су јавно доступни, тако да су остали у стању да провере или исправе пристрасност или оптимизују перформансе модела и употребу CO2.\n\nСазнајте више о Nextcloud етичком рангирању AI [у нашем блогу](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/).",
    "Status" : "Стање",
    "Machine learning models have been downloaded successfully." : "Успешно су преузети модели машинског учења.",
    "The machine learning models still need to be downloaded (see below)." : "Још увек је потребно да се преузму модели машинског учења (погледајте испод).",
    "Could not execute python. You may need to set the path to a working executable manually. (See below.)" : "Не може да се изврши python извршни фајл. Вероватно је потребно да ручно поставите путању до исправног извршног фајла. (Погледајте испод.)",
    "Background Jobs are not executed via cron. This app requires background jobs to be executed via cron." : "Позадински послови се не извршавају са cron. Ова апликација захтева да се позадински послови извршавају са cron.",
    "The app was installed successfully and will transcribe files in background processes on request." : "Апликација је успешно инсталирана и на захтев ће у позадинским процесима да транскрибује фајлове.",
    "Inference settings" : "Подешавања интерфејса",
    "The number of threads to use for inference (more is faster)" : "Број нити који се користи за закључивање (више је брже)",
    "Python" : "Python",
    "Checking Python" : "Проверава се Python",
    "Could not execute Python. You may need to set the path to a working executable manually." : "Не може да се покрене Python. Вероватно је потребно да ручно поставите путању до исправног извршног фајла.",
    "Python executable executed successfully and setup works." : "Python извршни фајл се успешно покренуо и ваша поставка функционише.",
    "If Python is not found automatically on your system for some reason you can set the path to the Python executable here. If you change this value, make sure to run occ maintenance:repair afterwards." : "Ако се Python из неког разлога не пронађе аутоматски на вашем систему, овде можете ручно да поставите путању до Python извршног фајла. Ако промените ову вредност, обавезно након тога извршите команду occ maintenance:repair.",
    "Failed to load settings" : "Грешка у дохватању поставки",
    "Failed to save settings" : "Грешка приликом чувања поставки"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
